### ISSUE TITLE
some cleanup TODOs I discovered during bigger merges

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#173]
# TODOs

- [x]  getAnnotationPreviews.xql --> l.39 & l.361 ff mri specifities?
- [x]  resources/css/EdiromOnlineRWA.css --> merge to CSS /SASS or remove
- [x]  getiFrameURL.xql --> l.26 & l.34 RWA specifities
- [x]  annotation.xqm --> l.136 RWA
- [x] meiP2html_rwaOnline.xsl
- [x] deep search for RWA stuff

**Comment by bwbohl** [comment]
@nikobeer could you please give me some assistance comparing `meiP2html.xsl` and `meiP2html_rwaOnline.xsl` the differences look reasonable but I'm lacking some test cases at the moment.

**Comment by bwbohl** [comment]
some occurrences of `RWA`and `rwa ` in scss and css files

**Comment by bwbohl** [comment]
> some occurrences of `RWA`and `rwa ` in scss and css files

@nikobeer what do you mean with "explosiv edirom windows" in EdiromOnlineRWA.css?

**Comment by bwbohl** [comment]
btw. EdiromOnlineRWA.css is just present in the repo but not referenced from other files

**Comment by riedde** [comment]
I had a look at the rwa css -> #192

**Comment by nikobeer** [comment]
@bwbohl as @riedde mentioned, this meiP2html_rwaOnline.xsl is just a copy that is currently used in RWA online to temporarily deactivate links within annotation texts.

**Comment by nikobeer** [comment]
@bwbohl & @riedde EdiromOnlineRWA.css is loaded in edirom's index.html as an additional css file. It contains project specific rules (annotations etc.) specific rules for XUL-Wrapper and electron.js Wrapper as well as some general edirom css bug fixes. Should be reviewed sometime in the future, especially because most fixes are not general fixes for all browsers but just for Mozilla/Firefox and/or Chrome. But for now it could just be deleted. General fixes should be reintegrated sometime in the future.
