### ISSUE TITLE
Remove unused xql files

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#366]
- [x]  getAnnotationParticipants.xql (sameAs #324 )

**Comment by daniel-jettka** [comment]
What's the way to check?

Like this? `find . -name "*.xql" > xqlfiles`

and then for all, e.g.: `grep -R  "pre-install.xql" *`

**Comment by bwbohl** [comment]
could be a feasible solution would like to see the list of deletion candidates you come up with!

**Comment by daniel-jettka** [comment]
Deletion candidates:

- [ ] getAnnotationParticipants.xql (sameAs #324 )
- [ ] loginToTextGrid.xql (sameAs #322 )
- [ ] checkTextGridLogin.xql (sameAs #322 )
- [ ] getAnnotationsInRendering.xql
- [ ] controller.xql

**Comment by peterstadler** [comment]
what about `getRendering.xql`? is this still used?

**Comment by daniel-jettka** [comment]
> What's the way to check?
> 
> Like this? `find . -name "*.xql" > xqlfiles`
> 
> and then for all, e.g.: `grep -R "pre-install.xql" *`

```
find . -name "*.xql" | while read -r line ; do
   echo "*** $line"
   grep -R "${line##*/}" * 
done
```

**Comment by daniel-jettka** [comment]
> what about `getRendering.xql`? is this still used? (I couldn't find any reference to it)

Yes, thank you for checking! Unfortunately I have just missed it, it seems.
