### ISSUE TITLE
integrate FreiDi audioView

### ISSUE THREAD

**Issue by bwbohl** [Edirom/Edirom-Online#99]

**Comment by daniel-jettka** [comment]
**Sustainability Check**

- [ ] regard [sustainability recommendations](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope) (refer to sustainability criteria by sust.crit.x below)
- [x] there are no ready-to-use solutions elsewhere ([sust.crit.1)](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#01-recherche) -> there are solutions but not one which provides everything we need (normally no track list and only limited interaction/configuration provided)

**Create a Web component for the audio player**

- [x] create separate GitHub repository ([sust.crit.5](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#01-recherche))
- [ ] version planning ([sust.crit.3](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#03-software-management), [sust.crit.5](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#01-recherche)) - [Milestone for Edirom Audio Player 0.1](https://github.com/Edirom/edirom-audio-player/milestone/1)
- [ ] document in JSDoc ([sust.crit.2](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#02-dokumentation))
- [ ] software management plan ([sust.crit.3](https://docs.nfdi4culture.de/ta3-sustainable-research-software/action-scope#03-software-management) [SMP in RDMO](https://rdmo.uni-paderborn.de/projects/77/))
<<<<<<<<<<<<<<<<
Current example: Freischütz Digital > Aufnahmen

Current source code:
- https://github.com/Edirom/Edirom-Online/tree/develop/app/view/window/audio
- https://github.com/Edirom/Edirom-Online/tree/develop/app/controller/window/audio
- https://github.com/Edirom/Edirom-Online/blob/develop/add/data/xql/getAudioPlayer.xql
